// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpqarwcpmeucncfojiex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcWFyd2NwbWV1Y25jZm9qaWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjA1OTMsImV4cCI6MjA3MjIzNjU5M30.TZllnSxXxikOPUTsZ5pKJxzUjLzeKvWDwdZbWN1OCJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});